import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faCheckCircle,
  faTimesCircle,
  faClock,
  faExclamationCircle,
  faEnvelope,
  faLock,
  faUserAlt,
  faBuilding,
  faPhone,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faFilePdf,
  faFileImage,
  faFileAlt,
  faFile,
  faPlus,
  faSearch,
  faFilter,
  faDownload,
  faSpinner,
  faHistory,
  faCloudUploadAlt,
  faTrash,
  faHourglass,
  faCalendarAlt,
  faEdit,
  faPrint,
  faUserTie,
  faBell,
  faBars,
  faTimes,
  faUser,
  faHome,
  faChartBar,
  faCog,
  faSignOutAlt,
  faUsers,
  faClipboardList
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library
library.add(
  faCheckCircle,
  faTimesCircle,
  faClock,
  faExclamationCircle,
  faEnvelope,
  faLock,
  faUserAlt,
  faBuilding,
  faPhone,
  faEye,
  faEyeSlash,
  faArrowLeft,
  faFilePdf,
  faFileImage,
  faFileAlt,
  faFile,
  faPlus,
  faSearch,
  faFilter,
  faDownload,
  faSpinner,
  faHistory,
  faCloudUploadAlt,
  faTrash,
  faHourglass,
  faCalendarAlt,
  faEdit,
  faPrint,
  faUserTie,
  faBell,
  faBars,
  faTimes,
  faUser,
  faHome,
  faChartBar,
  faCog,
  faSignOutAlt,
  faUsers,
  faClipboardList
);

export { FontAwesomeIcon }; 